import { Video, VideoResult } from './types';

// eslint-disable-next-line import/prefer-default-export
export const videoData: Video = {
  adult: false,
  backdrop_path: '/oqP1qEZccq5AD9TVTIaO6IGUj7o.jpg',
  belongs_to_collection: null,
  budget: 60000000,
  genres: [
    {
      id: 14,
      name: 'Fantasy',
    },
    {
      id: 28,
      name: 'Action',
    },
    {
      id: 12,
      name: 'Adventure',
    },
  ],
  homepage: 'https://kotzmovie.com',
  id: 455476,
  imdb_id: 'tt6528290',
  original_language: 'en',
  original_title: 'Knights of the Zodiac',
  overview:
    'When a headstrong street orphan, Seiya, in search of his abducted sister unwittingly taps into hidden powers, he discovers he might be the only person alive who can protect a reincarnated goddess, sent to watch over humanity. Can he let his past go and embrace his destiny to become a Knight of the Zodiac?',
  popularity: 2396.968,
  poster_path: '/qW4crfED8mpNDadSmMdi7ZDzhXF.jpg',
  production_companies: [
    {
      id: 11341,
      logo_path: '/xytTBODEy3p20ksHL4Ftxr483Iv.png',
      name: 'Stage 6 Films',
      origin_country: 'US',
    },
    {
      id: 5542,
      logo_path: '/ayE4LIqoAWotavo7xdvYngwqGML.png',
      name: 'Toei Animation',
      origin_country: 'JP',
    },
  ],
  production_countries: [
    {
      iso_3166_1: 'JP',
      name: 'Japan',
    },
    {
      iso_3166_1: 'US',
      name: 'United States of America',
    },
  ],
  release_date: '2023-04-27',
  revenue: 6794519,
  runtime: 112,
  spoken_languages: [
    {
      english_name: 'English',
      iso_639_1: 'en',
      name: 'English',
    },
    {
      english_name: 'Hungarian',
      iso_639_1: 'hu',
      name: 'Magyar',
    },
  ],
  status: 'Released',
  tagline: 'Go beyond your destiny.',
  title: 'Knights of the Zodiac',
  video: false,
  vote_average: 6.518,
  vote_count: 301,
} as Video;

export const videoNow: VideoResult = {
  dates: {
    maximum: '2023-07-11',
    minimum: '2023-05-24',
  },
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: '/oqP1qEZccq5AD9TVTIaO6IGUj7o.jpg',
      genre_ids: [14, 28, 12],
      id: 455476,
      original_language: 'en',
      original_title: 'Knights of the Zodiac',
      overview:
        'When a headstrong street orphan, Seiya, in search of his abducted sister unwittingly taps into hidden powers, he discovers he might be the only person alive who can protect a reincarnated goddess, sent to watch over humanity. Can he let his past go and embrace his destiny to become a Knight of the Zodiac?',
      popularity: 3355.755,
      poster_path: '/qW4crfED8mpNDadSmMdi7ZDzhXF.jpg',
      release_date: '2023-04-27',
      title: 'Knights of the Zodiac',
      video: false,
      vote_average: 6.5,
      vote_count: 301,
    },
    {
      adult: false,
      backdrop_path: '/4HodYYKEIsGOdinkGi2Ucz6X9i0.jpg',
      genre_ids: [28, 12, 16, 878],
      id: 569094,
      original_language: 'en',
      original_title: 'Spider-Man: Across the Spider-Verse',
      overview:
        'After reuniting with Gwen Stacy, Brooklyn’s full-time, friendly neighborhood Spider-Man is catapulted across the Multiverse, where he encounters the Spider Society, a team of Spider-People charged with protecting the Multiverse’s very existence. But when the heroes clash on how to handle a new threat, Miles finds himself pitted against the other Spiders and must set out on his own to save those he loves most.',
      popularity: 1542.139,
      poster_path: '/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg',
      release_date: '2023-05-31',
      title: 'Spider-Man: Across the Spider-Verse',
      video: false,
      vote_average: 8.5,
      vote_count: 2026,
    },
    {
      adult: false,
      backdrop_path: '/wRxLAw4l17LqiFcPLkobriPTZAw.jpg',
      genre_ids: [28, 53],
      id: 697843,
      original_language: 'en',
      original_title: 'Extraction 2',
      overview:
        "Tasked with extracting a family who is at the mercy of a Georgian gangster, Tyler Rake infiltrates one of the world's deadliest prisons in order to save them. But when the extraction gets hot, and the gangster dies in the heat of battle, his equally ruthless brother tracks down Rake and his team to Vienna, in order to get revenge.",
      popularity: 1422.453,
      poster_path: '/7gKI9hpEMcZUQpNgKrkDzJpbnNS.jpg',
      release_date: '2023-06-09',
      title: 'Extraction 2',
      video: false,
      vote_average: 7.6,
      vote_count: 1168,
    },
    {
      adult: false,
      backdrop_path: '/woJbg7ZqidhpvqFGGMRhWQNoxwa.jpg',
      genre_ids: [28, 12, 878],
      id: 667538,
      original_language: 'en',
      original_title: 'Transformers: Rise of the Beasts',
      overview:
        'When a new threat capable of destroying the entire planet emerges, Optimus Prime and the Autobots must team up with a powerful faction known as the Maximals. With the fate of humanity hanging in the balance, humans Noah and Elena will do whatever it takes to help the Transformers as they engage in the ultimate battle to save Earth.',
      popularity: 1301.343,
      poster_path: '/gPbM0MK8CP8A174rmUwGsADNYKD.jpg',
      release_date: '2023-06-06',
      title: 'Transformers: Rise of the Beasts',
      video: false,
      vote_average: 7.3,
      vote_count: 564,
    },
    {
      adult: false,
      backdrop_path: '/9n2tJBplPbgR2ca05hS5CKXwP2c.jpg',
      genre_ids: [16, 10751, 12, 14, 35],
      id: 502356,
      original_language: 'en',
      original_title: 'The Super Mario Bros. Movie',
      overview:
        'While working underground to fix a water main, Brooklyn plumbers—and brothers—Mario and Luigi are transported down a mysterious pipe and wander into a magical new world. But when the brothers are separated, Mario embarks on an epic quest to find Luigi.',
      popularity: 1256.912,
      poster_path: '/qNBAXBIQlnOThrVvA6mA2B5ggV6.jpg',
      release_date: '2023-04-05',
      title: 'The Super Mario Bros. Movie',
      video: false,
      vote_average: 7.8,
      vote_count: 5398,
    },
    {
      adult: false,
      backdrop_path: '/cSYLX73WskxCgvpN3MtRkYUSj1T.jpg',
      genre_ids: [16, 35, 10751, 14, 10749],
      id: 976573,
      original_language: 'en',
      original_title: 'Elemental',
      overview:
        'In a city where fire, water, land and air residents live together, a fiery young woman and a go-with-the-flow guy will discover something elemental: how much they have in common.',
      popularity: 1072.694,
      poster_path: '/8riWcADI1ekEiBguVB9vkilhiQm.jpg',
      release_date: '2023-06-14',
      title: 'Elemental',
      video: false,
      vote_average: 7.5,
      vote_count: 333,
    },
    {
      adult: false,
      backdrop_path: '/osnvZffaZymubHiBkOsIFd8Y3Re.jpg',
      genre_ids: [28, 27, 53],
      id: 986070,
      original_language: 'en',
      original_title: 'The Wrath of Becky',
      overview:
        'Two years after she escaped a violent attack on her family, 16-year-old Becky attempts to rebuild her life in the care of an older woman -- a kindred spirit named Elena. However, when a violent group known as the Noble Men break into their home, attack them and take their beloved dog, Becky must return to her old ways to protect herself and her loved ones.',
      popularity: 759.396,
      poster_path: '/3LShl6EwqptKIVq6NWOZ0FbZHEe.jpg',
      release_date: '2023-05-26',
      title: 'The Wrath of Becky',
      video: false,
      vote_average: 6.8,
      vote_count: 65,
    },
    {
      adult: false,
      backdrop_path: '/yF1eOkaYvwiORauRCPWznV9xVvi.jpg',
      genre_ids: [878, 28, 12],
      id: 298618,
      original_language: 'en',
      original_title: 'The Flash',
      overview:
        "When his attempt to save his family inadvertently alters the future, Barry Allen becomes trapped in a reality in which General Zod has returned and there are no Super Heroes to turn to. In order to save the world that he is in and return to the future that he knows, Barry's only hope is to race for his life. But will making the ultimate sacrifice be enough to reset the universe?",
      popularity: 786.283,
      poster_path: '/rktDFPbfHfUbArZ6OOOKsXcv0Bm.jpg',
      release_date: '2023-06-13',
      title: 'The Flash',
      video: false,
      vote_average: 6.7,
      vote_count: 733,
    },
    {
      adult: false,
      backdrop_path: '/8FhKnPpql374qyyHAkZDld93IUw.jpg',
      genre_ids: [9648, 53, 878],
      id: 536437,
      original_language: 'en',
      original_title: 'Hypnotic',
      overview:
        'A detective becomes entangled in a mystery involving his missing daughter and a secret government program while investigating a string of reality-bending crimes.',
      popularity: 760.613,
      poster_path: '/3IhGkkalwXguTlceGSl8XUJZOVI.jpg',
      release_date: '2023-05-11',
      title: 'Hypnotic',
      video: false,
      vote_average: 6.3,
      vote_count: 281,
    },
    {
      adult: false,
      backdrop_path: '/lQzSMhkAl90iXPirjnLbRHkxApC.jpg',
      genre_ids: [27],
      id: 917007,
      original_language: 'en',
      original_title: 'Bed Rest',
      overview: "A pregnant woman on bed rest begins to wonder if her house is haunted or if it's all in her head.",
      popularity: 732.221,
      poster_path: '/tiZF8b9T9fMcwvsEEkJ5ik1wCnV.jpg',
      release_date: '2022-12-08',
      title: 'Bed Rest',
      video: false,
      vote_average: 6.7,
      vote_count: 71,
    },
    {
      adult: false,
      backdrop_path: '/35z8hWuzfFUZQaYog8E9LsXW3iI.jpg',
      genre_ids: [12, 28, 14],
      id: 335977,
      original_language: 'en',
      original_title: 'Indiana Jones and the Dial of Destiny',
      overview:
        "Finding himself in a new era, approaching retirement, Indy wrestles with fitting into a world that seems to have outgrown him. But as the tentacles of an all-too-familiar evil return in the form of an old rival, Indy must don his hat and pick up his whip once more to make sure an ancient and powerful artifact doesn't fall into the wrong hands.",
      popularity: 740.388,
      poster_path: '/Af4bXE63pVsb2FtbW8uYIyPBadD.jpg',
      release_date: '2023-06-28',
      title: 'Indiana Jones and the Dial of Destiny',
      video: false,
      vote_average: 6.5,
      vote_count: 422,
    },
    {
      adult: false,
      backdrop_path: '/fCw8CVgII6W7ALbIh0SgXax3Hsj.jpg',
      genre_ids: [12, 10751, 14, 10749],
      id: 447277,
      original_language: 'en',
      original_title: 'The Little Mermaid',
      overview:
        'The youngest of King Triton’s daughters, and the most defiant, Ariel longs to find out more about the world beyond the sea, and while visiting the surface, falls for the dashing Prince Eric. With mermaids forbidden to interact with humans, Ariel makes a deal with the evil sea witch, Ursula, which gives her a chance to experience life on land, but ultimately places her life – and her father’s crown – in jeopardy.',
      popularity: 675.554,
      poster_path: '/ym1dxyOk4jFcSl4Q2zmRrA5BEEN.jpg',
      release_date: '2023-05-18',
      title: 'The Little Mermaid',
      video: false,
      vote_average: 6.3,
      vote_count: 832,
    },
    {
      adult: false,
      backdrop_path: '/eTvN54pd83TrSEOz6wbsXEJktCV.jpg',
      genre_ids: [10752, 28, 53],
      id: 882569,
      original_language: 'en',
      original_title: "Guy Ritchie's The Covenant",
      overview:
        'During the war in Afghanistan, a local interpreter risks his own life to carry an injured sergeant across miles of grueling terrain.',
      popularity: 544.105,
      poster_path: '/kVG8zFFYrpyYLoHChuEeOGAd6Ru.jpg',
      release_date: '2023-04-19',
      title: "Guy Ritchie's The Covenant",
      video: false,
      vote_average: 7.8,
      vote_count: 934,
    },
    {
      adult: false,
      backdrop_path: '/9t0tJXcOdWwwxmGTk112HGDaT0Q.jpg',
      genre_ids: [27, 53],
      id: 890771,
      original_language: 'en',
      original_title: 'The Black Demon',
      overview:
        "Oilman Paul Sturges' idyllic family vacation turns into a nightmare when they encounter a ferocious megalodon shark that will stop at nothing to protect its territory. Stranded and under constant attack, Paul and his family must somehow find a way to get his family back to shore alive before it strikes again in this epic battle between humans and nature.",
      popularity: 545.26,
      poster_path: '/uiFcFIjig0YwyNmhoxkxtAAVIL2.jpg',
      release_date: '2023-04-26',
      title: 'The Black Demon',
      video: false,
      vote_average: 6.2,
      vote_count: 263,
    },
    {
      adult: false,
      backdrop_path: '/o9bbojtrrpl0yriiTmzC3Lp3OhA.jpg',
      genre_ids: [28, 10752],
      id: 840326,
      original_language: 'fi',
      original_title: 'Sisu',
      overview:
        'Deep in the wilderness of Lapland, Aatami Korpi is searching for gold but after he stumbles upon Nazi patrol, a breathtaking and gold-hungry chase through the destroyed and mined Lapland wilderness begins.',
      popularity: 520.792,
      poster_path: '/ygO9lowFMXWymATCrhoQXd6gCEh.jpg',
      release_date: '2023-01-27',
      title: 'Sisu',
      video: false,
      vote_average: 7.5,
      vote_count: 889,
    },
    {
      adult: false,
      backdrop_path: '/jOkXeuLo4MBMpeoMa1ClAfTkxuI.jpg',
      genre_ids: [27, 9648, 53],
      id: 614479,
      original_language: 'en',
      original_title: 'Insidious: The Red Door',
      overview:
        "To put their demons to rest once and for all, Josh Lambert and a college-aged Dalton Lambert must go deeper into The Further than ever before, facing their family's dark past and a host of new and more horrifying terrors that lurk behind the red door.",
      popularity: 488.646,
      poster_path: '/azTC5osYiqei1ofw6Z3GmUrxQbi.jpg',
      release_date: '2023-07-05',
      title: 'Insidious: The Red Door',
      video: false,
      vote_average: 6.5,
      vote_count: 14,
    },
    {
      adult: false,
      backdrop_path: '/cKE9qZqYtF4jimf0GFOqKfy7NEU.jpg',
      genre_ids: [35, 10749],
      id: 884605,
      original_language: 'en',
      original_title: 'No Hard Feelings',
      overview:
        'On the brink of losing her childhood home, Maddie discovers an intriguing job listing: wealthy helicopter parents looking for someone to “date” their introverted 19-year-old son, Percy, before he leaves for college. To her surprise, Maddie soon discovers the awkward Percy is no sure thing.',
      popularity: 417.982,
      poster_path: '/5xeNPGbM8ImVdJACUoGpXT8Pxx3.jpg',
      release_date: '2023-06-15',
      title: 'No Hard Feelings',
      video: false,
      vote_average: 6.5,
      vote_count: 137,
    },
    {
      adult: false,
      backdrop_path: '/euO884625eFLfKLoc0MtFs5QiOS.jpg',
      genre_ids: [9648, 53, 28],
      id: 1070802,
      original_language: 'en',
      original_title: 'Confidential Informant',
      overview:
        'During a crack epidemic two narcotics agents hunting for a cop killer. Hoping for leads, Moran and Thorton pay off a junkie informant. To provide for his wife and son, Moran involves the stool pigeon in a deadly scheme. This causes the partners to come under the scrutiny of a suspicious internal affairs agent.',
      popularity: 408.062,
      poster_path: '/kCyAyqF6TKylJFuddaHtqq20b62.jpg',
      release_date: '2023-06-27',
      title: 'Confidential Informant',
      video: false,
      vote_average: 6.4,
      vote_count: 16,
    },
    {
      adult: false,
      backdrop_path: '/ajIgkZtZ2mme1vYbrfKSV2ddOuq.jpg',
      genre_ids: [27],
      id: 1083858,
      original_language: 'en',
      original_title: 'The Angry Black Girl and Her Monster',
      overview:
        'Vicaria is a brilliant teenager who believes death is a disease that can be cured. After the brutal and sudden murder of her brother, she embarks on a dangerous journey to bring him back to life.',
      popularity: 377.425,
      poster_path: '/4c3rU9R5oYexKFWaAHAc195B0RN.jpg',
      release_date: '2023-06-09',
      title: 'The Angry Black Girl and Her Monster',
      video: false,
      vote_average: 6.7,
      vote_count: 9,
    },
    {
      adult: false,
      backdrop_path: '/rogeBJK44LtWynOqzMFmEF30T80.jpg',
      genre_ids: [16, 14, 28, 12],
      id: 812225,
      original_language: 'ja',
      original_title: '映画 ブラッククローバー 魔法帝の剣',
      overview:
        'As a lionhearted boy who can’t wield magic strives for the title of Wizard King, four banished Wizard Kings of yore return to crush the Clover Kingdom.',
      popularity: 336.12,
      poster_path: '/9YEGawvjaRgnyW6QVcUhFJPFDco.jpg',
      release_date: '2023-06-16',
      title: 'Black Clover: Sword of the Wizard King',
      video: false,
      vote_average: 8.4,
      vote_count: 148,
    },
  ],
  total_pages: 81,
  total_results: 1606,
};
